const cities = [
  {city: 'San Francisco'},
  {city: 'Seattle'},
  {city: 'London'},
  {city: 'New York'},
  {city: 'Beijing'},
  {city: 'Dubai'},
  {city: 'Hong Kong'},
  {city: 'Paris'},
  {city: 'Shanghai'},
  {city: 'Singapore'},
  {city: 'Sydney'},
  {city: 'San Jose'},
  {city: 'Tokyo'},
  {city: 'Bangkok'},
  {city: 'Chicago'},
  {city: 'Los Angeles'},
  {city: 'Miami'},
  {city: 'Toronto'},
  {city: 'Mexico City'},
  {city: 'Mumbai'},
  {city: 'Zurich'},
  {city: 'Jakarta'},
  {city: 'Moscow'},
  {city: 'Sao Paulo'},
  {city: 'Singapore'},
  {city: 'Berlin'},
  {city: 'Thailand'},
  {city: 'Boston'},
  {city: 'Amsterdam'},
  {city: 'Boston'},
  {city: 'Seoul'},
  {city: 'Madrid'},
  {city: 'Washington, D.C.'},
  {city: 'Osaka'},
  {city: 'Phoenix'},
  {city: 'Philadelphia'},
  {city: 'San Diego'},
  {city: 'San Antonio'},
  {city: 'Dallas'},
  {city: 'Austin'},
  {city: 'Jacksonville'},
  {city: 'Fort Worth'},
  {city: 'Columbus'},
  {city: 'Charlotte'},
  {city: 'Indianapolis'},
  {city: 'Denver'},
  {city: 'Washington'},
  {city: 'El Paso'},
  {city: 'Detroit'},
  {city: 'Portland'},
  {city: 'Las Vegas'},
  {city: 'Memphis'},
  {city: 'Louisville'},
  {city: 'Baltimore'},
  {city: 'Milwaukee'},
  {city: 'Sacramento'},
  {city: 'Atlanta'},
  {city: 'San Mateo'},
  {city: 'Fremont'},
  {city: 'Oakland'},
  {city: 'Honolulu'},
  {city: 'Riverside'},
  {city: 'Irvine'},
  {city: 'Newark'},
  {city: 'Salt Lake'},
]

export default cities;